Предварительная сборка проекта
teacher-army/teacher-army pull request #13
Opened 2021-11-18 12:56 UTC by Rapieree

2021-11-18 13:23 UTC, zeckson commented on package.json
> +    "next": "12.0.4",
Может стоит поставить `typescript`?

2021-11-18 14:24 UTC, kicumkicum commented on package.json
> +    "next": "12.0.4",
Предлагаю сделать это позже. Мне кажется сейчас для @Rapieree это будет повышенной сложностью

2021-11-19 07:27 UTC, kicumkicum reviewed
Выглядит все круто! Это промежуточное ревью, Пока на него можно сильно не отвлекаться

2021-11-19 07:27 UTC, kicumkicum commented on src/pages/index.jsx
> +const Home = () => {
Возможно это будет домашняя страница пользователя. Пока не понятно

2021-11-19 07:51 UTC, Rapieree commented on next.config.js
> +  reactStrictMode: true,
Строгий режим, как я понял какие-то проверки в глубинах реакта на предмет ошибок и использования неактуальных подходов.

2021-11-19 07:57 UTC, Rapieree commented on src/pages/index.jsx
> +const Home = () => {
Хорошо, понял, просто пока удобнее корневой считать лендинг, или чисто компонент переименовать на Main?

2021-11-26 14:26 UTC, kicumkicum requested changes
Офигенно! Есть замечания, но в основном все круто! Наверно посмотрел половину, не все

2021-11-26 14:26 UTC, kicumkicum commented on src/components/features/features.jsx
> +const content = featuresContent;
Такое переименование выглядит странно. Если это действительно нужно, то лучше сделать непосредственно при импорте, или в непосредственной близости к месту использования.

2021-11-26 14:26 UTC, kicumkicum commented on src/components/footer/footer.jsx
> +const content = footerContent;
Та же история

2021-11-26 14:26 UTC, kicumkicum commented on src/components/idea/idea.jsx
> +const content = ideaContent;
+

2021-11-26 14:26 UTC, kicumkicum commented on src/components/layout/layout.jsx
> +
Лишний перенос

2021-11-26 14:26 UTC, kicumkicum commented on src/components/layout/layout.jsx
> +
Два переноса

2021-11-26 14:26 UTC, kicumkicum commented on src/components/layout/layout.jsx
> +        {!main ? <Header className="container" /> : ``}
Лучше возвращать `null`, потому что часто мы рендерим что-то или null. Хотя может он в этом кейсе превратится в строку. Но кажется, что не должен

```suggestion
        {!main ? <Header className="container" /> : null}
```

2021-11-26 14:26 UTC, kicumkicum commented on src/components/linksList/links-list.jsx
> +
Лишний перенос

2021-11-26 14:26 UTC, kicumkicum commented on src/components/promo/promo.jsx
> +const content = promoContent;
--

2021-11-26 14:26 UTC, kicumkicum commented on src/components/promo/promo.jsx
> +import {promoContent} from "./promo-content";
FYI Вообще контент лучше бы через пропсы передавать. Потому что компоненты привыкли получать данные через пропсы. Это сильно развязывает руки, потому что в таком случае данные можно хранить где угодно, хоть в константах, хоть на сервере.

Но прямо сейчас переделывать не нужно. Задача то сделана. Это просто к сведению. Когда упремся в это, тогда и переделаем. Может и не упремся совсем

2021-11-26 14:26 UTC, kicumkicum commented on src/components/site-nav/site-nav.jsx
> +  const getItemLinkClasses = (hrefLink, activeUrl, islight) => {
Если функцию можно сделать чистой и вынести за пределы тела компонентов, то так и нужно сделать. То бишь между импортами и компонентом. Это делает его тело компактнее и призывает делать именно чистые функции

2021-11-26 14:26 UTC, kicumkicum commented on src/components/slider/slider.jsx
> +  };
Сделай ее чистой и вынеси за пределы тела компонента

2021-11-26 14:26 UTC, kicumkicum commented on src/components/socials/socials.jsx
> +const content = socialsContent;
--

2021-11-26 14:26 UTC, kicumkicum commented on src/components/stars-rating-view/stars-rating-view.jsx
> +  };
Сделай ее чистой

2021-11-26 14:26 UTC, kicumkicum commented on package.json
> +    "sharp": "0.29.3"
А он где-то явно используется? Не смог понять

2021-11-26 14:26 UTC, kicumkicum commented on src/components/stars-rating-view/stars-rating-view.jsx
> +      {getStars().map((star) => star)}
Не очень понятно, зачем такой `map`

2021-11-26 14:26 UTC, kicumkicum commented on src/components/statistics/statistics.jsx
> +const content = statisticsContent;
--

2021-11-26 14:26 UTC, kicumkicum commented on src/components/statistics/statistics.jsx
> +const Statistics = ({className}) => {
Где-то на этом этапе в гитхабе сломалась подсветка синтаксиса)))) Большой ПР получился

2021-11-26 14:26 UTC, kicumkicum commented on src/components/subscribe-form/subscribe-form.jsx
> +import CustomButton from "../custom-button/custom-button";
Посмотрел до сюда. Остальное позже

2021-11-26 15:28 UTC, Rapieree commented
Посмотрел комментарии, всё понятно, исправлю в понедельник.

2021-11-26 17:44 UTC, kicumkicum requested changes
Досмотрел. Добавил еще несколько комментов

2021-11-26 17:44 UTC, kicumkicum commented on src/components/subscribe/subscribe.jsx
> +const content = subscribeContent;
--

2021-11-26 17:44 UTC, kicumkicum commented on src/components/subscribe/subscribe-content.js
> +  title: `NEWSLETTER`,
Если оно капсом, потому что должно так отображаться в интерфейсе, то это неверный подход. Данные стоит хранить в естественном виде. А их отображение регулировать стилями

2021-11-26 17:44 UTC, kicumkicum commented on src/components/tariffs/tariffs-content.js
> +    icon: <FireSvg width="29" height="38" />,
В данных не должно быть компонентов. Такие данные в интернет не отправишь и не получишь. Тут нужно хранить путь или название иконки. А компоненты использовать уже в jsx

2021-11-26 17:44 UTC, kicumkicum commented on src/components/tariffs/tariffs.jsx
> +const content = tariffsContent;
--

2021-11-26 17:44 UTC, kicumkicum commented on src/components/tariffs/tariffs.jsx
> +const content = tariffsContent;
Это можно фиксить не руками, а автозаменой с использованием регулярки

2021-11-26 17:44 UTC, kicumkicum commented on src/components/techs/techs.module.css
> +.list {
А они не должны быть вложенными в `.tech`? Я просто спрашиваю

2021-11-26 17:44 UTC, kicumkicum commented on src/components/user-reviews/user-reviews.jsx
> +const content = userReviewsContent;
--

2021-11-28 12:00 UTC, kicumkicum commented on src/components/user-reviews/user-reviews.jsx
> +const content = userReviewsContent;
Я посмотрел на next.js. И подумал, что можно этот `content` перенести в `getStaticProps`. Тогда некст будет еще на сервере добавлять его в разметку. Это изменение сделает компонент корректным, с той точки зрения, что он будет получать данные через пропсы. И если мы захотим что-то поменять или протестировать компоненты, то это будет не больно. А в текущей реализации тестировать будет проблематично. Потом объясню почему, это лучше голосом.

```js
import content from './abc';

const UserReviews = ({content, someProp}) => {/*...*/};

export const getStaticProps = () => {
  return {
    props: { content },
  }
}
```

2021-11-28 12:33 UTC, Rapieree commented on next.config.js
> +module.exports = withReactSvg({
Понял, исправлю на:

`const withReactSvg = require(`next-react-svg`);
const path = require(`path`);

const nextConfig = withReactSvg({
  include: path.resolve(__dirname, `src/assets/svg`),
  webpack(config, options) {
    return config;
  },
});
nextConfig.reactStrictMode = true;

module.exports = nextConfig;`

2021-11-28 12:38 UTC, Rapieree commented on src/components/custom-button/custom-button.jsx
> +const CustomButton = ({children, className, ...state}) => {
Понял, разберу на конкретные пропсы

2021-11-28 12:39 UTC, Rapieree commented on src/components/layout/layout.jsx
> +        {!main ? <Header className="container" /> : ``}
Исправлю на null

2021-11-28 12:41 UTC, Rapieree commented on src/components/stars-rating-view/stars-rating-view.jsx
> +      {getStars().map((star) => star)}
Исправлю на {getStars()}

2021-11-28 12:43 UTC, Rapieree commented on src/components/subscribe/subscribe-content.js
> +  title: `NEWSLETTER`,
Понял, добавлю uppercase в стилях. Я не уверен был что в этом была необходимость, раз данные можно назвать моковыми.

2021-11-29 12:44 UTC, kicumkicum approved these changes

2021-11-29 12:45 UTC, merged