Feature/add tabs and slider logics
teacher-army/teacher-army pull request #14
Opened 2021-11-26 12:57 UTC by Rapieree

2021-11-28 11:51 UTC, kicumkicum requested changes
Выглядит очень хорошо. Круто!

Только при создании ПРа не забывай выставлять меня ревьювером - справа вверху. Так я буду получать уведомление на почту. А сейчас я просто зашел и случайно увидел.

- [ ] Использовать в качестве заголовка имя ветки норм, особенно когда имя ветки осмысленное. Но у тебя с этим проблем нет. Нужно только превратить `Feature/add` в `Add` и будет отлично.

2021-11-28 11:51 UTC, kicumkicum commented on src/components/tabs/tab.jsx
> +    React.Children.map(children, (child) => child)
А тут нужно клонировать чилдренов? Нельзя просто сделать `{children}`?

2021-11-28 11:51 UTC, kicumkicum commented on src/components/tabs/tabs.jsx
> +  const contents = React.Children.map((children), (child) => child.type.name === `Tab` ? child : undefined);
FYI Можно вернуть не `undefined`, а `null`, если так будет работать. Это немного вкусовщина, но я использую такое правило - если нужно вернуть "ничего", то я возвращаю `null`.

Это связано с тем, что иногда мы ошибаемся и видим на странице строку `null` или `undefined`. И в случае использования описанного приема, есть чуть больше информации. Если `null`, то мы что-то явно записали и можно искать по коду `null`. Если `undefined`, то мы что-то забыли проинициализировать или берем не существующее свойства, это более сложный кейс, поэтому просто читаем код

2021-11-28 12:23 UTC, Rapieree commented on src/components/tabs/tab.jsx
> +    React.Children.map(children, (child) => child)
В принципе это не клонирование, но да, так и сделаю, я залип похоже и не понял почему ошибка была, а на деле стоило <>{children}</> сделать

2021-11-28 12:26 UTC, Rapieree commented on src/components/tabs/tabs.jsx
> +  const contents = React.Children.map((children), (child) => child.type.name === `Tab` ? child : undefined);
Понял, я подумал в некоторых случаях null способен в 0 отрисовываться, а undefined точно нет.

2021-11-29 12:48 UTC, kicumkicum requested changes
Быстрый взгляд после мержа

2021-11-29 12:48 UTC, kicumkicum commented on src/components/custom-button/custom-button.jsx
> +const CustomButton = ({children, className, ...state}) => {
Нужны явные пропсы

2021-11-30 07:38 UTC, kicumkicum commented on src/components/custom-button/custom-button.jsx
> +const CustomButton = ({children, className, ...state}) => {
done

2021-11-30 07:38 UTC, kicumkicum approved these changes

2021-11-30 07:38 UTC, merged