Add feedback
teacher-army/teacher-army pull request #16
Opened 2021-11-30 15:06 UTC by Rapieree

2021-12-01 22:35 UTC, kicumkicum commented
> * [ ]  На какой аккаунт слать сообщения?

Пока в @kicumkicum. Потом акк заведем для входящих заявок. Что-нибудь вроде @teacherarmy.inbox

2021-12-02 09:49 UTC, Rapieree commented
TODO:
[ ] Добавить попап/сообщение о успешном подтверждении отправки фидбэка
[ ] Добавить попап/сообщение об ошибке отправки
[ ] Обработка ошибок бд
[ ] Обработка ошибок api

2021-12-02 10:07 UTC, kicumkicum commented
> TODO:
> 
> * [ ]  Добавить попап/сообщение о успешном подтверждении отправки фидбэка
> * [ ]  Добавить попап/сообщение об ошибке отправки

Чтобы не мучиться с романом, можно писать ответ прямо в саму форму

2021-12-02 18:12 UTC, Rapieree commented
коммент

2021-12-02 18:13 UTC, Rapieree commented
коммент

2021-12-03 21:05 UTC, kicumkicum requested changes
Очень круто! Столько концепций потрогал и технологий применил. И столько ресеча было. Задача сложная, но ты хорошо с ней справился 💪🚀

2021-12-03 21:05 UTC, kicumkicum commented on src/components/subscribe-form/subscribe-form.jsx
> -        <CustomButton type="submit">Subscribe</CustomButton>
А action нужен тут? Мы же в онсабмит данные отправляем

2021-12-06 10:17 UTC, Rapieree commented on src/utils/utils.js
> +    checkKeysObjects(feedbackData, feedbackModel) && checkPropsLengths(feedbackData, feedbackModel)
Удалил метод, в нём нет необходимости

2021-12-06 10:17 UTC, Rapieree commented on src/utils/utils.js
> +    if (obj[key].length > Number(sizeMap[key])) {
Удалил метод, в нём нет необходимости

2021-12-06 10:17 UTC, Rapieree commented on .eslintrc.json
> +    "no-alert": "off"
Исправил

2021-12-06 10:18 UTC, Rapieree commented on src/api/client-api.js
> +    return true;
Мне кажется лучше пусть в компоненте будет обработка ошибки/успешного ввода

2021-12-06 10:18 UTC, Rapieree commented on src/components/subscribe-form/subscribe-form.jsx
> +    alert(`Сообщение успешно отправлено!`);
Исправил

2021-12-06 10:18 UTC, Rapieree commented on src/pages/api/subscribe.js
> +    if (req.method === `POST`) {
Исправил

2021-12-06 10:18 UTC, Rapieree commented on src/pages/api/subscribe.js
> +    }
Исправил

2021-12-06 10:19 UTC, Rapieree commented on src/services/mongodb/api.js
> +}
Изменил структуру подключения бд, плюс нашел как можно без try/catch этот момент отловить

2021-12-06 10:22 UTC, Rapieree commented on src/services/mongodb/shemas.js
> +    minLength: [3, getMinLengthMessage(`name`, 3)],
Исправил

2021-12-06 10:22 UTC, Rapieree commented on src/services/mongodb/shemas.js
> +    minLength: [5, getMinLengthMessage(`contacts`, 5)],
Исправил

2021-12-06 10:22 UTC, Rapieree commented on src/utils/utils.js
> +const feedbackModel = {
Удалил его

2021-12-06 10:23 UTC, Rapieree commented on src/services/mongodb/shemas.js
> +    required: [true, getRequiredText(`required`)],
Исправил

2021-12-06 10:23 UTC, Rapieree commented on src/services/mongodb/shemas.js
> +    maxLength: [2000, getMaxLengthMessage(`message`, 2000)],
Исправил

2021-12-06 10:24 UTC, Rapieree commented on src/services/mongodb/api.js
> +export {Feedback};
При проверке валидации импортил.

2021-12-06 10:25 UTC, Rapieree commented on src/pages/prices.jsx
> +export const getStaticProps = async () => {
Изменил, но в примерах некста всегда асинхронным был, хотя может потому что там данные с cms получали.

2021-12-06 10:26 UTC, Rapieree commented on src/pages/contact.jsx
> +    }
Исправил

2021-12-06 10:26 UTC, Rapieree commented on src/pages/api/subscribe.js
> +  try {
ИМХО, исправил

2021-12-06 10:26 UTC, Rapieree commented on src/pages/api/subscribe.js
> +      for (let key in err.errors) {
Это объект, поэтому for in

2021-12-06 10:27 UTC, Rapieree commented on src/components/subscribe-form/subscribe-form.jsx
> -        <CustomButton type="submit">Subscribe</CustomButton>
Исправил

2021-12-06 10:50 UTC, kicumkicum commented on src/pages/prices.jsx
> +export const getStaticProps = async () => {
Скорее всего. Я видел примеры без асинка и с асинком наоборот пришлось искать))

2021-12-06 11:42 UTC, kicumkicum approved these changes
Льем!

2021-12-06 11:42 UTC, kicumkicum commented on src/models/feedback.js
> +export default Feedback;
FYI Сейчас править не надо, но в будущем я бы предложил использовать в серверной части только именованный экспорт. 

Зачастую появляются какие-то константы, которые приходится вытаскивать. Или не всегда понятно, какая сущность главнее, хотя это реже кейс. Но искать вхождения по проекту точно становится проще, потому что имена при импорте и экспорте точно совпадают. 

Ну и отпадает делема, делать именованный экспорт или по умолчанию))

2021-12-06 11:42 UTC, merged