Add pay page(WIP)
teacher-army/teacher-army pull request #19
Opened 2021-12-06 15:43 UTC by Rapieree

2021-12-06 20:00 UTC, Rapieree commented
```
Краткая инфа по moneta.assistant

ПАРАМЕТРЫ ПОЛУЧАЕМОГО ЗАПРОСА
MNT_ID: '29398836', - Идентификатор магазина в системе MONETA.RU.
MNT_TRANSACTION_ID: '37955628604026889322', - Внутренний идентификатор заказа, однозначно определяющий заказ в магазине.
MNT_OPERATION_ID: '551667552', - Номер операции в системе MONETA.RU.
MNT_AMOUNT: '1.00', - Фактическая сумма, полученная на оплату заказа, без учета комиссии за услуги системы «MONETA.RU», всегда 2 знака точности
MNT_CURRENCY_CODE: 'RUB', - ISO код валюты, в которой произведена оплата заказа в магазине
MNT_TEST_MODE: '0', - Если оплата произведена в тестовом режиме, то параметр содержит «1», если в реальном – «0».
MNT_SIGNATURE: '43195b1ad044f0d7b0c648c633caa1b2', - Код для идентификации отправителя и проверки целостности данных
paymentSystem_unitId: '2243990', - Идентификатор платежной системы, если оплата производилась с платежной системы отличной от «MONETA.RU».
MNT_CORRACCOUNT: '317' - Номер счета плательщика. Если оплата производилась с пользовательского счета в системе «MONETA.RU», то совпадает с MNT_USER.
MNT_CUSTOM1, MNT_CUSTOM2, MNT_CUSTOM3, - Другие параметры. Параметры, переданные в запросе на оплату через MONETA.Assistant
Параметры могут быть переданы методом POST или GET в зависимости от настроек расширенного счёта.

АЛГОРИТМ MD5
-- подпись при получении запроса
MNT_SIGNATURE = MD5(MNT_ID + MNT_TRANSACTION_ID + MNT_OPERATION_ID +
  MNT_AMOUNT + MNT_CURRENCY_CODE + MNT_SUBSCRIBER_ID + MNT_TEST_MODE
  + КОД ПРОВЕРКИ ЦЕЛОСТНОСТИ ДАННЫХ)
-- подпись при отправлении ответа (Расширенный ответ в формате xml?)
MNT_SIGNATURE = MD5( MNT_RESULT_CODE + MNT_ID + MNT_TRANSACTION_ID
  + КОД ПРОВЕРКИ ЦЕЛОСТНОСТИ ДАННЫХ )
-- Подпись на оплату
MNT_SIGNATURE = MD5(MNT_ID + MNT_TRANSACTION_ID + MNT_AMOUNT + MNT_CURRENCY_CODE +
  MNT_SUBSCRIBER_ID + ТЕСТОВЫЙ РЕЖИМ + КОД ПРОВЕРКИ ЦЕЛОСТНОСТИ ДАННЫХ)

КОДЫ ОТВЕТОВ:
200 - Заказ оплачен. Уведомление об оплате магазину доставлено.
100, 302, 402 - Отправка уведомления об оплате будет повторена. В течение суток запросы будут повторяться.
500 - Ошибка обработки. Автоматическая отправка уведомлений будет остановлена. Необходимо связаться с группой поддержки MONETA.RU.

Отправка ответа: 2 варианта

1) SUCCESS / FAIL (При FAIL магазин не обработал уведомление об оплате, повтор уведомлений)
2) Ответ в XML формате.

<?xml version="1.0" encoding="UTF-8"?>
<MNT_RESPONSE>
  <MNT_ID></MNT_ID> - Идентификатор магазина в системе MONETA.RU.
  <MNT_TRANSACTION_ID></MNT_TRANSACTION_ID> - Внутренний идентификатор заказа, однозначно определяющий заказ в магазине
  <MNT_RESULT_CODE></MNT_RESULT_CODE> - Код ответа на запрос
  <MNT_DESCRIPTION></MNT_DESCRIPTION> - Описание состояния заказа. Задается в произвольной форме.
  <MNT_AMOUNT></MNT_AMOUNT> - Сумма оплаты
  <MNT_SIGNATURE></MNT_SIGNATURE> - Код для идентификации отправителя и проверки целостности данных
  <MNT_ATTRIBUTES> - Содержит произвольные параметры, которые будут сохранены в операции.
    <ATTRIBUTE> - Элемент представляет один произвольный параметр операции
      <KEY></KEY> - Уникальное название параметра операции. Может быть произвольным и не должно превышать 32 символа.
      <VALUE></VALUE> - Значение параметра операции.
    </ATTRIBUTE>
  </MNT_ATTRIBUTES>
</MNT_RESPONSE>

ПАРАМЕТРЫ ЗАПРОСА ИЗ ФОРМЫ
URL: https://www.payanyway.ru/assistant.htm
Method: POST/GET - настройка в кабинете?
Content-Type: `application/json` ?
body: {
  MNT_ID - required, Идентификатор магазина в системе MONETA.RU
  MNT_AMOUNT - required, Сумма оплаты. Десятичные символы отделяются точкой. Количество знаков после запятой - максимум два символа.
  MNT_TRANSACTION_ID - unrequired, Внутренний идентификатор заказа, если не указать, сам сгенерирует 20-ти значный идентификатор заказа
  MNT_CURRENCY_CODE - unrequired, ISO код валюты, в которой производится оплата заказа в магазине, (RUB, USD, EUR)
  MNT_TEST_MODE - unrequired, дефолтное - 0
  MNT_DESCRIPTION - unrequired, Описание оплаты. Максимальная длина 500 символов.
  MNT_SUBSCRIBER_ID - unrequired, Внутренний идентификатор пользователя, однозначно определяющий получателя в учетной системе магазина.
  MNT_SIGNATURE - unrequired, сигнатура, обязательно MNT_TRANSACTION_ID, если указать, магазин сверит со своей сигнатурой, если не сойдутся - ошибка
  MNT_CUSTOM1, MNT_CUSTOM2, MNT_CUSTOM3 - unrequired, будут в запросе на подверждение оплаты, (думаю использовать для ФИО, Мыла, номера телефона)
  MNT_SUCCESS_URL - unrequired, переход будет при успешной оплате, независимо от нашего ответа, по умолчанию https://www.moneta.ru/paymentSuccess.htm.,
  MNT_FAIL_URL - unrequired, URL страницы магазина, куда должен попасть покупатель после отмененной или неуспешной оплаты, по умолчанию https://www.moneta.ru/paymentFail.htm
  MNT_RETURN_URL - unrequired, URL страницы магазина, куда должен вернуться покупатель при добровольном отказе от оплаты
  moneta.locale - Язык пользовательского интерфейса, (ru / en)
  paymentSystem.unitId - Предварительный выбор платежной системы. Список - https://www.moneta.ru/viewPaymentMethods.htm
  paymentSystem.limitIds - Список идентификаторов платежных систем, которые необходимо показывать пользователю в MONETA.Assistant. (формат - "1015,1017")
}
```

2021-12-13 06:33 UTC, kicumkicum commented
С этими кейсами кажется разобрались. Да?
> Редирект назад на сайт
> Отправить чек об оплате клиенту на почту

2021-12-13 06:34 UTC, Rapieree commented
Ага, щас отредакчу

2021-12-13 08:22 UTC, kicumkicum requested changes
Крутотень! В полу шаге от миллиона, как говорится))) 🎯

2021-12-13 08:22 UTC, kicumkicum commented on src/pages/api/payment.js
> +// key from magazine
Не сразу понятно, что за магазин. magazine это журнал))

Лучше вот так `payanyway market key`

2021-12-13 08:22 UTC, kicumkicum commented on src/pages/api/payment.js
> +    console.log(`Request no method GET`);
Как это работает? Когда случается этот кейс? Он нам нужен?

2021-12-13 08:22 UTC, kicumkicum commented on src/pages/api/payment.js
> +      console.log(`Get verify request?`);
Что предполагает эта ветка? Она нам нужна? Почему ок если мы не добавили данные в базу?

2021-12-13 08:22 UTC, kicumkicum commented on src/pages/api/payment.js
> +        if (String(controlHash) === String(MNT_SIGNATURE)) {
Тут нужно оборачивать в `String`? Изначально это не строки?

2021-12-13 08:22 UTC, kicumkicum commented on src/pages/api/payment.js
> +          console.log(`ALL OK: BD, SIGNATURES`);
Объяви в `utils` или выше функцию `log` и используй ее. Так будет понятно, что это продакшен логи, а не остаток от дебага. Ее содержимое в будущем изменится, но начнем с простого.

```js
const log = (...args) => {
  console.log(...args);
};
```

2021-12-13 08:41 UTC, Rapieree commented on src/components/custom-input/custom-input.jsx
> +    <input className={`${customInputStyle.input} ${classname}`} {...nativeInputProps} />
Я думал об этом, но custom-input слишком обширно звучит, по идее и без label возможно, и label разной функциональности, не урегулировал пока этот момент. Сейчас это отдельные компоненты, и я планировал их отдельно сводить в местах использования.

2021-12-13 08:44 UTC, Rapieree commented on src/components/header/header.jsx
> +      <SiteNav light={!light}/>
Да, светлая шапка - темное меню, темная шапка - светлое меню

2021-12-13 10:13 UTC, Rapieree commented on src/pages/api/payment.js
> +    console.log(`Request no method GET`);
По идее, я получал только запросы метода GET, нужна или нет данная обработка, трудно сказать, я не уверен пока в этом магазине, что он там слать будет при различных исходах. Эта обработка чисто для нас, опять же статус 200 чисто из-за неуверенности. В любом случае, он не подкреплен сообщением "SUCCESS/FAIL", поэтому не будет воспринят как принятый запрос об оплате.

2021-12-13 10:31 UTC, Rapieree commented on src/components/layout/layout.jsx
> +const Layout = ({main, children, content, className}) => {
Понял, попробую разобраться в этом получше

2021-12-14 06:44 UTC, kicumkicum requested changes
Давай. Последний короткий заход и льем 💪🏽 🚀

2021-12-14 06:44 UTC, kicumkicum commented on src/api/client-api.js
> +  const response = await fetch(`/api/subscribe`, {
FYI Можно было оставить константу, просто поменяв ее на пустую строку

2021-12-14 06:44 UTC, kicumkicum commented on src/models/feedback.js
> +  learnDuration: feedbackValidOptions.learnDuration,
А если чувак напишет `8 лет`, имея ввиду разработку? Как название поля будет коррелировать с этой информацией?

2021-12-14 06:44 UTC, kicumkicum commented on src/models/feedback.js
> +// Создаем новую модель или используем уже имеющуюся
Это в коде написано, строчкой ниже. Комментарий должен рассказывать зачем написан неочевидный код. А что делает код видно по самому коду. В редких случаях не видно, в каких-то зубодробительных алгоритмах, но тут в целом понятно. Не понятно зачем.

2021-12-14 06:44 UTC, kicumkicum commented on src/pages/api/payment.js
> +  customLog(req.query);
Почему у тебя все `custom`? Просто `log`)

2021-12-14 06:44 UTC, kicumkicum commented on src/api/client-api.js
> +  const response = await fetch(`/api/subscribe`, {
Ну может коммент еще добавить, почему она пустая

2021-12-14 06:49 UTC, Rapieree commented on src/models/feedback.js
> +  learnDuration: feedbackValidOptions.learnDuration,
На что поменять тогда?

2021-12-14 06:52 UTC, Rapieree commented on src/api/client-api.js
> +  const response = await fetch(`/api/subscribe`, {
А зачем, не понимаю, думаю и так понятно что это внутреннее api по слешу. Константа изначально была задумана потому что я хотел из одного места управлять конечной точкой для разных мест, а раз это невозможно, да и скорее исключение из правил тот случай с передачей абсолютного url, мне кажется не имеет смысла константу задавать, которая никогда не будет использоваться

2021-12-14 06:55 UTC, Rapieree commented on src/pages/api/payment.js
> +  customLog(req.query);
Исправлю, просто у меня сниппет для console.log с подобным названием, библиотека Sharp имеет идентичный метод, и ещё какая-то, полминуты пытался понять какой автоимпорт будет верным

2021-12-14 07:46 UTC, Rapieree commented on src/api/client-api.js
> +  const response = await fetch(`/api/subscribe`, {
DevelopmentTime

2021-12-14 08:10 UTC, Rapieree commented on src/models/feedback.js
> +  learnDuration: feedbackValidOptions.learnDuration,
developmentTime

2021-12-14 09:14 UTC, kicumkicum approved these changes

2021-12-14 09:14 UTC, merged