Add about page
teacher-army/teacher-army pull request #22
Opened 2021-12-14 13:26 UTC by Rapieree

2021-12-14 17:41 UTC, kicumkicum commented on src/pages/about.jsx
> +const LINKS = {
Обычно, такие собирательные объекты относят к енумам из языков со строгой типизацией. И именуются они камелкейсом с большой буквы. А ключи ты верно именовал

2021-12-14 17:42 UTC, kicumkicum commented on src/pages/about.jsx
> +  ISSUE: `https://github.com/kicumkicum/teacher-army/issues`,
Если отсортируешь их по алфавиту, то навигировать по ним будет проще

2021-12-14 17:43 UTC, kicumkicum commented on src/pages/about.jsx
> +  ISSUE: `https://github.com/kicumkicum/teacher-army/issues`,
Это часть ревью, но проскачил одиночным комментом

2021-12-14 17:44 UTC, kicumkicum requested changes
Круто, быстро, молодежно))

2021-12-14 18:52 UTC, Rapieree commented on src/pages/about.jsx
> +const LINKS = {
Понял, буду знать

2021-12-14 18:53 UTC, Rapieree commented on src/pages/about.jsx
> +  ISSUE: `https://github.com/kicumkicum/teacher-army/issues`,
Сделаю

2021-12-15 07:48 UTC, kicumkicum approved these changes

2021-12-15 07:48 UTC, merged