Add blog page(WIP)
teacher-army/teacher-army pull request #23
Opened 2021-12-15 09:23 UTC by Rapieree

2021-12-16 14:24 UTC, kicumkicum requested changes
Оч круто! Двадцать строк кода и блог готов. Огоньогоньогонь!

2021-12-16 14:24 UTC, kicumkicum commented on src/components/post-preview/post-preview.jsx
> +    }
FYI Можно еще отказаться от if-else совсем, оставив только вызовы сеттеров

2021-12-16 14:24 UTC, kicumkicum commented on src/components/post-preview/post-preview.jsx
> +    }
Можно даже оставить только один стейт. И текст для кнопки вычислять на его основе

2021-12-16 14:24 UTC, kicumkicum commented on src/lib/markdown.js
> +const fs = require(`fs`);
Давай его подключать тоже с импортом

2021-12-16 14:24 UTC, kicumkicum commented on src/lib/markdown.js
> +  const fileText = await fs.readFileSync(mdFilePath, `utf-8`);
Если синк, то авайт не нужон. Если авайт, но нужон асинхронное чтение

2021-12-16 14:24 UTC, kicumkicum commented on src/lib/markdown.js
> +  const htmlText = await unified().use(remarkParse).use(remarkGFM).use(remarkHtml).process(markdownText);
Такие цепочки, чейны, лучше писать столбиком.

```js

await unified()
  .use(foo)
  .use(bar)
```

2021-12-16 14:24 UTC, kicumkicum commented on src/lib/markdown.js
> +  const fileText = await fs.readFileSync(mdFilePath, `utf-8`);
Ну и тут можно сразу вернуть результат, без переменной `return await fs.readFile()`

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/about.jsx
> +  const aboutContentPath = path.resolve(`src/content/markdown/about/about.md`);
Давай оформим его как константу вверху модуля

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/about.jsx
> +  const aboutContentPath = path.resolve(`src/content/markdown/about/about.md`);
Строку я имею ввиду

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/about.jsx
> +  const path = require(`path`);
Вообще, так делать не принято, импортировать не вверху. Язык позволяет, но это не очень хорошо. Вверху ты видешь импорты сразу, а в середине как повезет. Можем мы тут отказаться от `path` совсем?

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/about.jsx
> +  const aboutContentPath = path.resolve(`src/content/markdown/about/about.md`);
Два костыля - два коммента. Но лучше костыль переместить в одно место. Тогда можно будет и комментом одним обойтись

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/blog.jsx
> +  const fs = require(`fs/promises`);
Те же комменты про импорт внутри функции

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/blog.jsx
> +  const fs = require(`fs/promises`);
И может от них можно отказаться, если перенести низкоуровневую работу в какие-нибудь utils

2021-12-16 14:24 UTC, kicumkicum commented on src/pages/faq.jsx
> +        <div className={`inner-wrapper mrgb-80`}>
А что ты с faq делал?

2021-12-16 14:32 UTC, Rapieree commented on src/components/post-preview/post-preview.jsx
> +    }
С сеттером понятно, а это как с текстом?

```
      <CustomButton className={postPreviewStyle.showMoreButton} onClick={onShowMoreButtonClick}>
        {showMore ? ButtonText.HIDE : ButtonText.SHOW}
      </CustomButton>
```

2021-12-16 15:15 UTC, kicumkicum commented on src/components/post-preview/post-preview.jsx
> +    }
Ну да, вот так, как в твоём примере. Или можно переменную выше объявить

2021-12-16 15:16 UTC, kicumkicum commented on src/pages/about.jsx
> +  const path = require(`path`);
Ну да, типа кусок годы тут. А фронт там. А если это всё в функцию в другой модуль вынести? То импорт все равно тут писать?

2021-12-16 15:20 UTC, Rapieree commented on src/pages/faq.jsx
> +        <div className={`inner-wrapper mrgb-80`}>
Изменил обертку на более глобальную, чтоб страницы были похожи по стилям.

2021-12-16 15:26 UTC, Rapieree commented on src/pages/about.jsx
> +  const path = require(`path`);
В общем сделал другой вариант

2021-12-17 10:50 UTC, kicumkicum requested changes
Сорян, я подкинул еще немного предложений)

2021-12-17 10:50 UTC, kicumkicum commented on src/lib/markdown.js
> +    if (fileName.match(/[.md]$/)) {
Если можно обойтись без регулярки, то лучше так и сделать. Обычно люди сложно их читают. Есть метод `fileName.endWith('.md')` или типа того

2021-12-17 10:50 UTC, kicumkicum commented on src/pages/about.jsx
> +  const aboutContent = await getHtmlTextFromMarkdownFile(`src/content/markdown/about/about.md`);
Положи путь в константу

2021-12-17 10:50 UTC, kicumkicum commented on src/pages/blog.jsx
> +import React from "react";
Внешние зависимости стоит размещать вверху. Но вообще можно добавить правил линтера про алфавитной сортировке путей импорта и забыть об этой рутине

2021-12-17 10:50 UTC, kicumkicum commented on src/pages/blog.jsx
> +  const posts = await getHtmlTextArrayFromMarkdownDirectory(`src/content/markdown/blog/`);
Путь опять же в константу лучше положить

2021-12-17 10:50 UTC, kicumkicum commented on src/lib/markdown.js
> +import {unified} from "unified";
На созвоне я сказал, что `lib` норм название и сказанное сейчас может быть как противоречие, но тем не менее. Выносить файлы в директории следует тогда, когда этих файлов несколько. Ну хотя бы два, а лучше три. Это связано с тем, что когда файл один, нам сложно заглянуть в будущее и понять, в какой же директории ему лучше лежать. Еще очень мало опыта. А структура проекта рождается именно из опыта.

На основе опыта мы пытаемся сделать структуру, которой удобно пользоватся. Когда файл один - опыта мало. И велик риск, что структура будет не удобной. К тому же, ради одного файла утомительно лезть в папочку. Особенно чувствуешь это, когда у тебя много таких папочек с одним файлом.

Поэтому, проще сейчас положить файл в `src/`, а когда появятся несколько файлов в `src/`, тогда можно будет размышлять о директории

2021-12-17 10:50 UTC, kicumkicum commented on src/content/markdown/about/about.md
> +## Наставничество
Там ниже, я написал про подход с созданием директорий. Он подходит и для этого случая. Если у нас будет три страницы, которые будут содержать единичный md-контент, то получится, что у нас будет три папки с одним файлом. Будет утомительно их раскрывать и скрывать. С `blog` все понятно. У нас есть опыт и представление, что там будет много постов, все честно. Но с `about` нет такой уверенности. Скорее всего он будет один.

Поэтому, чтобы не переусложнять, проще положить в его в `src/content/markdown/about.md`.

Вообще, я бы и директорию `markdown` упразднил. Типа `scr/content/about.md`. Или `src/content/blog/post-01.md`. У тебя в коде есть проверка на расширение файла, поэтому делать так вполне безопасно. И работать с меньшей вложенностью сильно удобнее.

Возможно будет не удобно, что там лежат `.js` файлы и `.md`, но мы точно этого не знаем. Я бы попробовал. Может у нас все в md переедет. А может впоследствии на директории разделим. А может в cms переедет. А может что-то еще. Мы точно не знаем, поэтому сложно принимать решение о разделении

2021-12-17 11:45 UTC, kicumkicum approved these changes

2021-12-17 11:45 UTC, merged