Fix styles for pre release(WIP)
teacher-army/teacher-army pull request #27
Opened 2021-12-20 09:23 UTC by Rapieree

2021-12-20 20:37 UTC, kicumkicum requested changes
Крутяг! Не обязательно править сейчас. Можешь сначала основную работу сделать

2021-12-20 20:37 UTC, kicumkicum commented on src/components/header/header.jsx
> +import Link from "next/link";
Внешняя зависимость - вверх

2021-12-20 20:37 UTC, kicumkicum commented on src/components/linksList/links-list.jsx
> +import Link from "next/link";
```suggestion
import Link from "next/link";
import linksListStyle from "./link-list.module.css";
```

2021-12-20 20:37 UTC, kicumkicum commented on src/components/promo/promo.jsx
> +            <a href="#tariffs">
А почему тут `a`, а в других местах `Link`? Я просто не шарю

2021-12-20 20:37 UTC, kicumkicum commented on src/content/common/footer.js
> +        name: `Начало`,
Добавь тут где-нибудь `TODO` избавиться от дубрилования тут и в `const.js`, где у нас навигация описана

2021-12-21 06:32 UTC, Rapieree commented on src/components/promo/promo.jsx
> +            <a href="#tariffs">
По идее, здесь нет необходимости спец.компоненте, так как перемещение на одной странице. А так, Link для маршрутизации по страницам next, он предзагружает страницы по путям, я так понимаю кешем активно пользуется и так далее, <a> - для ссылок на внешние ресурсы, либо в этом случае просто якорь на одной странице.

2021-12-22 15:25 UTC, kicumkicum approved these changes
🚀 Круть вообще!

2021-12-22 15:26 UTC, kicumkicum commented
Ну кароч, я солью. А эти три таски отдельно. Комменты в коде у меня вызывают боль. Ну посмотрим, сколько мы с ними проживем. Может удалить было правильнее. А потом ревертнуть из истории. Ну ладно, так решили, так и делаем))

2021-12-22 15:26 UTC, merged