Send subscribe data to google sheets
teacher-army/teacher-army pull request #28
Opened 2021-12-20 09:27 UTC by kicumkicum

Сделано:

- [ ] Добавлена отправка данных в google таблицы, при поступлении заявки
- [ ] Добавлен dot-env и перенесены все обращения к `process.env` в файл `config.js`. Теперь они происходят неявно в dot-env

@Rapieree Проверь, пожалуйста, что БД и оплата работает как и прежде. Для этого скопируй `.env.sample` в `.env`. Возьми значения переменных для google sheets в сейфе `Server env`

2021-12-22 08:01 UTC, Rapieree commented on src/middleware/google-sheets.js
> +  }]);
Дату и время нужно перевести в часовой пояс Московский(+03:00) относительно UTC, 
timeRus: new Date().toLocaleString(ru-Ru, {timeZone: Europe/Moscow}), или попроще варианты

2021-12-22 08:03 UTC, Rapieree commented on src/pages/api/payment.js
>  import crypto from "crypto";
Сделать запись в таблицу для оплаты было бы неплохо ещё

2021-12-22 08:05 UTC, Rapieree commented on config.js
> +} = process.env;
Если можно будет обойтись файлом .env.local, next поддерживает чтение переменных окружения из него, то можно избавиться от dotenv

2021-12-22 08:06 UTC, Rapieree requested changes
В целом здорово выглядит, проще и читабельнее чем Mongoose

2021-12-22 11:36 UTC, kicumkicum commented on config.js
> +} = process.env;
Избавился

2021-12-22 11:37 UTC, kicumkicum commented on src/pages/api/payment.js
>  import crypto from "crypto";
Завел ишью

2021-12-22 11:44 UTC, kicumkicum commented on src/middleware/google-sheets.js
> +  }]);
done

2021-12-23 08:32 UTC, Rapieree commented on src/middleware/google-sheets.js
> +    .map((it) => it.trim());
Здорово, и читабельно

2021-12-23 08:33 UTC, Rapieree requested changes
Круто, осталось для оплаты сделать

2021-12-23 08:59 UTC, kicumkicum commented
> Круто, осталось для оплаты сделать

Я под это сделал отдельную ишью. На днях запилю, но морозить этот ПР из-за этого не стоит

2021-12-23 13:46 UTC, Rapieree approved these changes
Всё отлично!

2021-12-23 13:47 UTC, merged